version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=passop
      - AUTH_SECRET=${AUTH_SECRET:-passop_auth_dev}
      - AUTH_PASSWORD_HASH=${AUTH_PASSWORD_HASH}
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    restart: unless-stopped

  web:
    build:
      context: .
      args:
        - VITE_API_BASE=/
    environment:
      - VITE_API_BASE=/
    ports:
      - '5173:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
